version: "3"
services:
  config-front:
    image: registry.cn-beijing.aliyuncs.com/codeforfun/config-front:latest
    build: .
    container_name: config-front
    ports:
      - "80:80"
networks:
  default:
    external:
      name: local
